### ISSUE TITLE
[Request] Ability to change font + Scroll to a date

### ISSUE THREAD

**Issue by zaidiabbas** [Ljuka/CalendarDateRangePicker#5]
I need the ability to change the font for done/cancel buttons. Also, I need to open the picker by focusing on a specific date not scrolled to the top. To select the color of the current date to differentiate between it and other days (if it is included in the selected min-max dates).

**Comment by Ljuka** [comment]
Hi @zaidiabbas 

Thanks for submitting the issue. Every problem from your issue has been resolved **except** the one with selected colours. If you want you can fork the library, expend it and submit pull request. By the way, if you want to expend the library make sure that your code does not have conflicts with the current one.

Feel free to reopen the issue if you have more problems

**Comment by zaidiabbas** [comment]
The issue does not appear on iPhone 11 - iOS 13.6
