### ISSUE TITLE
[Issue] Issue with collectionView (Sliding)

### ISSUE THREAD

**Issue by zaidiabbas** [Ljuka/CalendarDateRangePicker#6]
As shown in the GIF when open the picker, when scrolling it slides to the right.
![ezgif-2-b5d36ee0a7a7](https://user-images.githubusercontent.com/18144118/87234623-7962e580-c3db-11ea-8c7b-ca3a1706165f.gif)

**Comment by Ljuka** [comment]
Can you tell me the model of iphone you are testing it? I tried multiple devices and simulators but couldn't recreate that behaviour.

**Comment by zaidiabbas** [comment]
> Can you tell me the model of iphone you are testing it? I tried multiple devices and simulators but couldn't recreate that behaviour.

iPhone 11 - iOS 13.5

**Comment by zaidiabbas** [comment]
The issue does not appear on iPhone 11 - iOS 13.6
