### ISSUE TITLE
range auto select

### ISSUE THREAD

**Issue by chitranjank** [Ljuka/CalendarDateRangePicker#7]
hello,
I need to auto select date from current to next three day and those days not be selectable like today date is 15 than 16,17,18 will not selectable 
please solve the problem
 thanks 
chitranjan

**Comment by Ljuka** [comment]
You have variable `disabledDates` for that. Check Example project for more information on how to implement that.

**Comment by chitranjank** [comment]
how to disable selected range?

**Comment by Ljuka** [comment]
> how to disable selected range?

Combine variable `disabledDates` with `selectedStartDate` and `selectedEndDate`

**Comment by chitranjank** [comment]
can you explain through example.
